# Generated by Django 5.2.15 on 2026-06-22 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('chain', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('admin', 'Admin Added'), ('user', 'User Submitted'), ('metadata', 'LayerZero Metadata')], default='metadata', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdfs/')),
                ('summary', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserAlertChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('discord', 'Discord Webhook')], max_length=20)),
                ('identifier', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DVNConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_eid', models.IntegerField()),
                ('required_dvn_count', models.IntegerField()),
                ('optional_dvn_threshold', models.IntegerField(default=0)),
                ('optional_dvn_count', models.IntegerField(default=0)),
                ('required_dvns', models.JSONField(default=list)),
                ('optional_dvns', models.JSONField(default=list)),
                ('confirmations', models.IntegerField(default=0)),
                ('is_exposed', models.BooleanField(default=True)),
                ('is_centralized', models.BooleanField(default=True)),
                ('has_low_confirmations', models.BooleanField(default=True)),
                ('has_proxy_admin_risk', models.BooleanField(default=False)),
                ('is_oracle_stale', models.BooleanField(default=False)),
                ('is_owner_eoa', models.BooleanField(default=False)),
                ('risk_notes', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('is_healthy', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.bridgecontract')),
            ],
            options={
                'ordering': ['-detected_at'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'remote_eid'), name='unique_contract_remote_eid')],
            },
        ),
        migrations.CreateModel(
            name='MonitoredOApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.bridgecontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_oapps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'contract'), name='unique_user_contract')],
            },
        ),
    ]
